### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Elkosscom** [Elkosscom/learning-python#2]
```
PdfReadWarning: Xref table not zero-indexed. ID numbers for objects will be corrected. [pdf.py:1865]
Traceback (most recent call last):
  File "Z:\git\learning-python\pdftools\split_by_page.py", line 129, in <module>
    split_pages(file)
  File "Z:\git\learning-python\pdftools\split_by_page.py", line 71, in split_pages
    for i in range(pdf_reader.getNumPages()):
  File "C:\Users\michalk\AppData\Local\Continuum\miniconda3\lib\site-packages\PyPDF3\pdf.py", line 1274, in getNumPages
    self._flatten()
  File "C:\Users\michalk\AppData\Local\Continuum\miniconda3\lib\site-packages\PyPDF3\pdf.py", line 1624, in _flatten
    catalog = self.trailer["/Root"].getObject()
  File "C:\Users\michalk\AppData\Local\Continuum\miniconda3\lib\site-packages\PyPDF3\generic.py", line 518, in __getitem__
    return dict.__getitem__(self, key).getObject()
  File "C:\Users\michalk\AppData\Local\Continuum\miniconda3\lib\site-packages\PyPDF3\generic.py", line 179, in getObject
    return self.pdf.getObject(self).getObject()
  File "C:\Users\michalk\AppData\Local\Continuum\miniconda3\lib\site-packages\PyPDF3\pdf.py", line 1725, in getObject
    % (indirectReference.idnum, indirectReference.generation, idnum, generation))
PyPDF3.utils.PdfReadError: Expected object ID (23 0) does not match actual (22 0); xref table not zero-indexed.
```

**Comment by Elkosscom** [comment]
added strict=False, works now.
